### ISSUE TITLE
Submit transactions in the same block

### ISSUE THREAD

**Issue by alex-matthe** [FuelLabs/block-explorer-v2#2]
### Q: Is there a way to force 2 transactions to be included in the same block?

I tried to send a request to `fuel-core` GraphQL API with this mutation in order to make the `submit` calls as close as possible
```
mutation Mutation($tx1: String!, $tx2: String!) {
  first: submit(tx: $tx1)
  second: submit(tx: $tx2)
}

```

The transactions were mined in the same second, but included in 2 different blocks.
  
<img width="575" alt="Screenshot 2021-10-17 at 03 17 41" src="https://user-images.githubusercontent.com/87020692/137605419-2330f822-9dc6-4edb-adc6-a974f1b170e8.png">

**Comment by adlerjohn** [comment]
Closing in favor of the fuel-core issue.
