### ISSUE TITLE
Comma-separate thousands

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/block-explorer-v2#39]
For decimal numbers (especially gas price) comma-separate on thousands.

- It's possible to use `formatUnits` and `parseUnits` from `ethers` lib.
- Use 3 decimal units
Refs.: https://github.com/FuelLabs/swayswap/pull/81

Examples:
<img width="600" alt="Screen Shot 2022-05-10 at 5 51 36 PM" src="https://user-images.githubusercontent.com/3941923/167719823-d824679e-79d6-4c53-96fa-89ccf93b9398.png">

**Comment by DJkal11** [comment]
I would like to attempt this issue. Could you assign it to me?
