### ISSUE TITLE
Remove env prop for API URL being cached

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/block-explorer-v2#79]
Changing `env` prop `GRAPHQL_API_ENDPOINT` is not working if you have accessed the project previously, unless you clear `localStorage` data.

This code is causing it:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/8636507/175077490-49829e74-2653-424d-99f4-811df310f3ce.png">

I think we should remove this code using API url saved in localStorage, unless I'm not seeing the use case for it

@luizstacio you see any problems on removing it?

Ref: #76

**Comment by adlerjohn** [comment]
I think the purpose of this was if the user had configured a custom endpoint, then it'll get saved and used by default?

Instead of removing the feature entirely, maybe make a default special case (maybe empty?) where the default is used, instead of saving the default as a custom endpoint.

**Comment by luizstacio** [comment]
We should add the feature: https://github.com/FuelLabs/block-explorer-v2/issues/74
